version: '3.8' # Specify the Docker Compose version

services:
  flask_app:
    build: .
    ports:
      - "5000:5000" # Map port 5000 of the host to port 5000 of the container
    environment:
      FLASK_ENV: development # Set the environment variable for Flask
    volumes:
      - .:/app # Mount the current directory to /app in the container
